before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ZxpVY1tAJr/G19hIyrnQmIttFfyJjyEBmEQbw/XGA9Cos6SQKGf6bRA5FEJGvgtLmWwfklXL9KoRqDe45SYn9eRULT1nI023KjBqkAvGlrLSOuuDXt0rFVjjCBHsQ1JMvvQ+UprADAMwiPwDts7t+VOwAlrQeuFsh1FNDoi4zizIHTyCqH+gerck6+Zxg1ze1JyawRvNI21YWebSbVB/Vrs3scP8t3WKJXv0KLbp4BKAuEO2jZpoiGXqhNt0XExkDAm82a86Tz6SBceva9iLYy39yDP63otNAtv9BY2TT/nIENYfdR5FObKfrI4eiK7vEdMzL6eYmL8YeZSzfpbr0SKLo94XQBSgPqNzfTYeljZ2xuSO1IvNcdpZoOunm1K4Rnmzz+vTiBZdf9ZENZhZ5omvarAHXJOiNajejXQlSQTSaPSt7gDcGIDcZ0R70RSQvzVAtxv/5eZ+E0X4w26y+DonSAMXcQlFTuSgl0C3fTutUFQPAbRbmu4pegYdPHB+y4SmzT55KdCItk72xlUoU7iVgz+KHVPhZR0bxGIrWkBWeSACO2CWvPRZHNPr3OFoMr3JUJCNntvNZiH13RG1uCO6ViF628SP0iLzChbtbqGFmaQ5Fppnj6yljjaFtk3NBmIJxEvAPA3uskahpWA+cIqVO+V7/Kq9vLC5SZDM+Qw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
